version: 0.2

phases:
  install:
    commands:
      - |
          dnf update
          dnf install -y yum-utils
          yum-config-manager --disable 'remi-php*'
          yum-config-manager --enable remi-php81
          dnf update

          dnf install -y php \
              php-cli \
              php-common \
              php-curl \
              php-dev \
              php-gd \
              php-mbstring \
              php-mysql \
              php-xml \
              php-openssl \
              php-pdo \
              php-pdo-mysql \
              php-json \
              php-session \
              php-filter \
              php-hash \
              php-ctype \
              php-xdebug \
              php-xdebug \
              make \
              unzip

          phpenmod xdebug

          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
          chmod +x /usr/local/bin/composer

  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install --no-progress

  post_build:
    commands:
      - echo Build completed on `date`

