---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins
spec:
  containers:
    - name: docker
      image: docker:latest
      command:
        - /bin/cat
      tty: true
      volumeMounts:
        - name: dind-certs
          mountPath: /certs
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: DOCKER_TLS_VERIFY
          value: 1
        - name: DOCKER_HOST
          value: tcp://localhost:2376
    - name: dind
      image: docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: dind-certs
          mountPath: /certs
    # - name: jnlp
    #   image: jenkins/inbound-agent:latest
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-certs
      emptyDir: {}

# apiVersion: v1
# kind: Pod
# spec:
#   containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
#     - name: docker
#       image: docker:latest
#       command:
#         - cat
#       tty: true
#       env:
#         - name: DOCKER_HOST
#           value: tcp://localhost:2375
#       volumeMounts:
#       - name: docker-sock
#         mountPath: /var/run/docker.sock
    
#     - name: jnlp
#       image: jenkins/jnlp-slave:4.13.3-1-jdk11

#   volumes:
#     - name: docker-sock
#       hostPath:
#         path: /var/run/docker.sock