apiVersion: v1
kind: Pod
spec:
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: docker:latest
      command: 
      - sleep
      args: ["30d"]
      volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
    
    - name: jnlp
      image: jenkins/jnlp-slave:4.13.3-1-jdk11

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock