apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  labels:
    app: kanboard
  namespace: kanboard-stage
spec:
  selector:
    app: kanboard
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    name: https

