apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  labels:
    app: kanboard
  namespace: kanboard-stage
spec:
  selector:
    app: kanboard
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: LoadBalancer

