apiVersion: v1
kind: Service
metadata:
  name: kanboard-service
  labels:
    app: kanboard
  namespace: kanboard-stage
spec:
  selector:
    app: kanboard
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http